server:
  port: 48080

# 默认的数据库名
database:
  name: dong
# 选择开发环境
profiles:
  active: local

security:
  salt: tech_π # 密码加盐, 更安全的做法是每个用户的密码使用独立的盐，并将其保存在用户表中
  salt-index: 3 # 盐插入的位置

yudao:
  info:
    version: 1.0.0
    base-package: cn.iocoder.dong
spring:
  application:
    name: dong